### ISSUE TITLE
bro when i try to open this using npm start it  will open just an white page what should I do now?

### ISSUE THREAD

**Issue by showmma-sho** [phanison898/facebook-clone#2]
[](url)
![clone issue](https://user-images.githubusercontent.com/81492167/114316019-41ffa180-9af1-11eb-8bf5-b0649cb3a010.PNG)

**Comment by phanison898** [comment]
Hello @Shows-creation 

Did you create **.env** file by adding firebase config values?
If not create a firebase project and add config values in .env file `(please read the README instructions)`

Incase if you already created .env file along with firebase config values, follow the below steps
1. Delete the existing repository (reason: you might be cloned the repo at the time I was pushing the new code)
2. Clone the repo freshly
3. Go to the cloned directory
4. Create .env file as explained earlier
5. Run the below commands
    - npm install
    - npm start

Let me know, if the error still exists 🙂

**Comment by Shows-creation** [comment]
![Uploading me 0111.PNG…]()

**Comment by Shows-creation** [comment]
![Uploading mioq.jpg…]()
Bro i also deployed this clone with firebase but the main problem is when I post some pictures or some comments. after that when i refresh the page every post that i did is gone. why it doesn't save any data of posting? how ccan i save all data of postijing

**Comment by showmma-sho** [comment]
**Bro i also deployed this clone with firebase but the main problem is when I post some pictures or some comments. after that when i refresh the page every post that i did is gone. why it doesn't save any data of posting? how can i save all posts data**

![Capture](https://user-images.githubusercontent.com/81492167/114465210-55386d00-9bd6-11eb-8e0a-fe55d0595203.JPG)

**Comment by phanison898** [comment]
Hello @Shows-creation 

I ran your deployed application and found below console error
![github_error_fb](https://user-images.githubusercontent.com/53811651/114469341-921e5700-9c0a-11eb-9a37-83c1afe68f0b.PNG)

It seems error coming from Firebase console.

Find the below similar issue thread. You might get the solution
<a href="https://github.com/firebase/firebase-js-sdk/issues/2923">Error Thread</a>

**Comment by showmma-sho** [comment]
I request you plz help me with this stuff. i  really didn't find the solution. can we plz meet on google meet or zoom, As a friendly request. you can send me a mail plzzz

**Comment by Shows-creation** [comment]
plz can we meet   via google meet or zoom app plz or  from discord only u
can help me

**Comment by phanison898** [comment]
@Shows-creation 

I understand your situation brother.

But I got a work to do on daily, which leaves me no time 😐 

But don't worry, I'll try to find a solution to your problem soon and will let you know in here (github) or in insta

**Comment by showmma-sho** [comment]
Or friend🥰🥰🥰🥰Sent from my Huawei phone-------- Original message --------From: Phanison ***@***.***>Date: Tue, 13 Apr 2021, 21:47To: phanison898/facebook-clone ***@***.***>Cc: Show ***@***.***>, Mention ***@***.***>Subject: Re: [phanison898/facebook-clone] bro when i try to open this using npm start it  will open just an white page what should I do now? (#2)

@Shows-creation

I understand your situation brother.

But I got a work to do on daily, which leaves me no time 😐

But don't worry, I'll try to find a solution to your problem soon and will let you know in here (github) or in insta
